version: 2

jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.2
        entrypoint: /bin/sh
    steps:
      - checkout
      - run:
          name: Validate tf files (terraform validate)
          command: find . -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (terraform validate -check-variables=false "$m" && echo "√ $m") || exit 1 ; done
      - run:
          name: check if all tf files are formatted (terraform fmt)
          command: if [ `terraform fmt | wc -c` -ne 0 ]; then echo "Some terraform files need be formatted, run 'terraform fmt' to fix"; exit 1; fi
      - run:
          name: "Install: tflint"
          command: |
              apk add wget
              wget https://github.com/wata727/tflint/releases/download/v0.5.4/tflint_linux_amd64.zip
              unzip tflint_linux_amd64.zip
              mkdir -p /usr/local/tflint/bin
              export PATH=/usr/local/tflint/bin:$PATH
              install tflint /usr/local/tflint/bin
      - run:
          name: "tflint check"
          command: /usr/local/tflint/bin/tflint

workflows:
  version: 2
  build:
    jobs:
      - build
